### ISSUE TITLE
error on debian 12

### ISSUE THREAD

**Issue by chuckgmthompson** [mkud/Remmina_mRemoteNG_conv#16]
when I tried to run it, I got this:
This program requires additional dependencies. Execute:

    pip3 install SecretStorage pycryptodomex

then when I ran pip3 install SecretStorage pycryptodomex, I got this: 
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install

so I ran this: pip3 install SecretStorage pycryptodomex --break-system-packages
Defaulting to user installation because normal site-packages is not writeable
Collecting SecretStorage
  Downloading SecretStorage-3.3.3-py3-none-any.whl (15 kB)
Collecting pycryptodomex
  Downloading pycryptodomex-3.19.0-cp35-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 12.4 MB/s eta 0:00:00
Requirement already satisfied: cryptography>=2.0 in /usr/lib/python3/dist-packages (from SecretStorage) (38.0.4)
Collecting jeepney>=0.6
  Downloading jeepney-0.8.0-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 kB 2.2 MB/s eta 0:00:00
Installing collected packages: pycryptodomex, jeepney, SecretStorage
Successfully installed SecretStorage-3.3.3 jeepney-0.8.0 pycryptodomex-3.19.0

Now when I run this: python3 remmina_mremoteng_conv.py -f nremote_all.xml, I got this: 
Traceback (most recent call last):
  File "/tmp/Remmina_mRemoteNG_conv-master/remmina_mremoteng_conv.py", line 471, in <module>
    main() 
    ^^^^^^
  File "/tmp/Remmina_mRemoteNG_conv-master/remmina_mremoteng_conv.py", line 399, in main
    if PassDecrypt(root.attrib["Protected"]) != 'ThisIsNotProtected':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/Remmina_mRemoteNG_conv-master/remmina_mremoteng_conv.py", line 240, in PassDecrypt
    plaintext = cipher.decrypt_and_verify(ciphertext, tag)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.local/lib/python3.11/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 567, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/home/chuck/.local/lib/python3.11/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed

I help would be appreciated.  thanks

**Comment by FSpark** [comment]
Maybe the number of iterations needs to be adjusted to `10000`, which works for me, as it is in the specific xml file.
```python
    key = hashlib.pbkdf2_hmac("sha1", key_from_mRemNG.encode(), salt, 10000, dklen=32)
```

**Comment by squadramunter** [comment]
> Maybe the number of iterations needs to be adjusted to `10000`, which works for me, as it is in the specific xml file.
> 
>     key = hashlib.pbkdf2_hmac("sha1", key_from_mRemNG.encode(), salt, 10000, dklen=32)

Wow! Thank you very much! That worked perfectly!
