### ISSUE TITLE
I'm not able to get it worked

### ISSUE THREAD

**Issue by kocercan** [mkud/Remmina_mRemoteNG_conv#3]
I'm very happy for I found this project. After few tries I can't get over this error. My system is Linux Mint 19.3 

$python3 remmina_mremoteng_conv.py -f vf-ptt.xml
Traceback (most recent call last):
  File "remmina_mremoteng_conv.py", line 225, in <module>
    main() 
  File "remmina_mremoteng_conv.py", line 193, in main
    recursion_for_get_group_name([], root)
  File "remmina_mremoteng_conv.py", line 125, in recursion_for_get_group_name
    recursion_for_get_group_name(cur_group_name + [cur_node.attrib['Name']], cur_node)
  File "remmina_mremoteng_conv.py", line 125, in recursion_for_get_group_name
    recursion_for_get_group_name(cur_group_name + [cur_node.attrib['Name']], cur_node)
  File "remmina_mremoteng_conv.py", line 147, in recursion_for_get_group_name
    PassDecrypt(cur_node.attrib['Password']), True)
  File "/home/ercan/.local/lib/python3.6/site-packages/secretstorage/collection.py", line 115, in create_item
    self.ensure_not_locked()
  File "/home/ercan/.local/lib/python3.6/site-packages/secretstorage/collection.py", line 55, in ensure_not_locked
    raise LockedException('Collection is locked!')
secretstorage.exceptions.LockedException: Collection is locked!

**Comment by mkud** [comment]
I tryed to produce this error.
Do you have this dialog box when you first start remmina?

![VirtualBox_mint_29_06_2020_15_51_36](https://user-images.githubusercontent.com/5719212/86007896-bc5aab80-ba20-11ea-8122-79d5bae30b71.png)

**Comment by kocercan** [comment]
I've never seen this "unlock login keyring" prompt before.

**Comment by kocercan** [comment]
I just found a solution for this. I've unlocked keyring via "passwords and keys(Sea Horse)" right click login and choose unlock. The script finished without any error.  When I check remmina I saw the script only imported ssh entries. It just ignores entries with Protocol="RDP" I think.
