### ISSUE TITLE
Conversion failed

### ISSUE THREAD

**Issue by yuljk** [mkud/Remmina_mRemoteNG_conv#5]
Hi - When attempting to convert my mRemoteNG file I receive the following error and the conversion process fails.

Traceback (most recent call last):
  File "remmina_mremoteng_conv.py", line 225, in <module>
    main() 
  File "remmina_mremoteng_conv.py", line 193, in main
    recursion_for_get_group_name([], root)
  File "remmina_mremoteng_conv.py", line 125, in recursion_for_get_group_name
    recursion_for_get_group_name(cur_group_name + [cur_node.attrib['Name']], cur_node)
  File "remmina_mremoteng_conv.py", line 147, in recursion_for_get_group_name
    PassDecrypt(cur_node.attrib['Password']), True)
  File "remmina_mremoteng_conv.py", line 112, in PassDecrypt
    cipher = Cryptodome.Cipher.AES.new(key, Cryptodome.Cipher.AES.MODE_GCM, nonce=nonce)
  File "/usr/local/lib/python3.8/dist-packages/Cryptodome/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/Cryptodome/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/Cryptodome/Cipher/_mode_gcm.py", line 620, in _create_gcm_cipher
    return GcmMode(factory, key, nonce, mac_len, kwargs, ghash_c)
  File "/usr/local/lib/python3.8/dist-packages/Cryptodome/Cipher/_mode_gcm.py", line 188, in __init__
    raise ValueError("Nonce cannot be empty")
ValueError: Nonce cannot be empty

Any help would be much appreciated.

**Comment by iamjosharmstrong** [comment]
Hey all, im getting the same as above. It has imported my SSH connections but left out all my groups/folders and RDP connections..
Im fairly new to linux, moving over from Windows running Dual boot with Pop OS. I pulled the .py script and ran python3 remmina_mremoteng_conv.py -f rdp.xml with both the .py and the .xml in the same folder. 

Any help would be great!

josh@pop-os:~/Downloads$ python3 remmina_mremoteng_conv.py -f rdp.xml
Traceback (most recent call last):
  File "remmina_mremoteng_conv.py", line 225, in <module>
    main() 
  File "remmina_mremoteng_conv.py", line 193, in main
    recursion_for_get_group_name([], root)
  File "remmina_mremoteng_conv.py", line 125, in recursion_for_get_group_name
    recursion_for_get_group_name(cur_group_name + [cur_node.attrib['Name']], cur_node)
  File "remmina_mremoteng_conv.py", line 125, in recursion_for_get_group_name
    recursion_for_get_group_name(cur_group_name + [cur_node.attrib['Name']], cur_node)
  File "remmina_mremoteng_conv.py", line 147, in recursion_for_get_group_name
    PassDecrypt(cur_node.attrib['Password']), True)
  File "remmina_mremoteng_conv.py", line 112, in PassDecrypt
    cipher = Cryptodome.Cipher.AES.new(key, Cryptodome.Cipher.AES.MODE_GCM, nonce=nonce)
  File "/home/josh/.local/lib/python3.8/site-packages/Cryptodome/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/home/josh/.local/lib/python3.8/site-packages/Cryptodome/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/home/josh/.local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 620, in _create_gcm_cipher
    return GcmMode(factory, key, nonce, mac_len, kwargs, ghash_c)
  File "/home/josh/.local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 188, in __init__
    raise ValueError("Nonce cannot be empty")
ValueError: Nonce cannot be empty

**Comment by fxrsliberty** [comment]
Me too! 

jtremblay@JT-Fedora-WKSTN Remmina_mRemoteNG_conv-master]$ python3 remmina_mremoteng_conv.py -f jt_11_16_20.xml 
Traceback (most recent call last):
  File "/home/jtremblay/Remmina_mRemoteNG_conv-master/remmina_mremoteng_conv.py", line 225, in <module>
    main() 
  File "/home/jtremblay/Remmina_mRemoteNG_conv-master/remmina_mremoteng_conv.py", line 193, in main
    recursion_for_get_group_name([], root)
  File "/home/jtremblay/Remmina_mRemoteNG_conv-master/remmina_mremoteng_conv.py", line 125, in recursion_for_get_group_name
    recursion_for_get_group_name(cur_group_name + [cur_node.attrib['Name']], cur_node)
  File "/home/jtremblay/Remmina_mRemoteNG_conv-master/remmina_mremoteng_conv.py", line 147, in recursion_for_get_group_name
    PassDecrypt(cur_node.attrib['Password']), True)
  File "/home/jtremblay/Remmina_mRemoteNG_conv-master/remmina_mremoteng_conv.py", line 112, in PassDecrypt
    cipher = Cryptodome.Cipher.AES.new(key, Cryptodome.Cipher.AES.MODE_GCM, nonce=nonce)
  File "/usr/lib64/python3.9/site-packages/Cryptodome/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/Cryptodome/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/lib64/python3.9/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 620, in _create_gcm_cipher
    return GcmMode(factory, key, nonce, mac_len, kwargs, ghash_c)
  File "/usr/lib64/python3.9/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 188, in __init__
    raise ValueError("Nonce cannot be empty")
ValueError: Nonce cannot be empty

**Comment by mkud** [comment]
Could you give me more information what system (Linux version) are you using?

I installed Fedora 33 on the new VM, install Remmina aplication.

Then:

    [maxx@localhost Downloads]$ python3 remmina_mremoteng_conv.py  -f ASSD_ASUPR.xml 
    This program requires additional dependencies. Execute:

        pip3 install SecretStorage pycryptodomex

    to install all the necessary dependencies

Then:

    pip3 install SecretStorage pycryptodomex

and in finish:

    [maxx@localhost Downloads]$ python3 remmina_mremoteng_conv.py  -f mRemoteNG_example.xml 
    All OK

**Comment by zondaryota** [comment]
Have the same issue on Ubu 20.04
Have a few levels of incaplulation of folders in mRemoteNG.
For Example: NameOfProduct > Prod / Test > DataCenter > Servers (SSH&RDP mixed) 

Analizing:

ihms@ihms:~/Downloads/Remmina_mRemoteNG_conv-master$ pip3 install SecretStorage pycryptodomex
Requirement already satisfied: SecretStorage in /usr/lib/python3/dist-packages (2.3.1)
Requirement already satisfied: pycryptodomex in /home/ihms/.local/lib/python3.8/site-packages (3.10.1)

And then 

ihms@ihms:~/Downloads/Remmina_mRemoteNG_conv-master$ python3 remmina_mremoteng_conv.py -f servers.xml
Traceback (most recent call last):
  File "remmina_mremoteng_conv.py", line 225, in <module>
    main() 
  File "remmina_mremoteng_conv.py", line 193, in main
    recursion_for_get_group_name([], root)
  File "remmina_mremoteng_conv.py", line 125, in recursion_for_get_group_name
    recursion_for_get_group_name(cur_group_name + [cur_node.attrib['Name']], cur_node)
  File "remmina_mremoteng_conv.py", line 125, in recursion_for_get_group_name
    recursion_for_get_group_name(cur_group_name + [cur_node.attrib['Name']], cur_node)
  File "remmina_mremoteng_conv.py", line 125, in recursion_for_get_group_name
    recursion_for_get_group_name(cur_group_name + [cur_node.attrib['Name']], cur_node)
  [Previous line repeated 1 more time]
  File "remmina_mremoteng_conv.py", line 147, in recursion_for_get_group_name
    PassDecrypt(cur_node.attrib['Password']), True)
  File "remmina_mremoteng_conv.py", line 112, in PassDecrypt
    cipher = Cryptodome.Cipher.AES.new(key, Cryptodome.Cipher.AES.MODE_GCM, nonce=nonce)
  File "/home/ihms/.local/lib/python3.8/site-packages/Cryptodome/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/home/ihms/.local/lib/python3.8/site-packages/Cryptodome/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/home/ihms/.local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 620, in _create_gcm_cipher
    return GcmMode(factory, key, nonce, mac_len, kwargs, ghash_c)
  File "/home/ihms/.local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 188, in __init__
    raise ValueError("Nonce cannot be empty")
ValueError: Nonce cannot be empty

**Comment by zondaryota** [comment]
> Have the same issue on Ubu 20.04
> Have a few levels of incaplulation of folders in mRemoteNG.
> For Example: NameOfProduct > Prod / Test > DataCenter > Servers (SSH&RDP mixed)
> 
> Analizing:
> 
> ihms@ihms:~/Downloads/Remmina_mRemoteNG_conv-master$ pip3 install SecretStorage pycryptodomex
> Requirement already satisfied: SecretStorage in /usr/lib/python3/dist-packages (2.3.1)
> Requirement already satisfied: pycryptodomex in /home/ihms/.local/lib/python3.8/site-packages (3.10.1)
> 
> And then
> 
> ihms@ihms:~/Downloads/Remmina_mRemoteNG_conv-master$ python3 remmina_mremoteng_conv.py -f servers.xml
> Traceback (most recent call last):
> File "remmina_mremoteng_conv.py", line 225, in
> main()
> File "remmina_mremoteng_conv.py", line 193, in main
> recursion_for_get_group_name([], root)
> File "remmina_mremoteng_conv.py", line 125, in recursion_for_get_group_name
> recursion_for_get_group_name(cur_group_name + [cur_node.attrib['Name']], cur_node)
> File "remmina_mremoteng_conv.py", line 125, in recursion_for_get_group_name
> recursion_for_get_group_name(cur_group_name + [cur_node.attrib['Name']], cur_node)
> File "remmina_mremoteng_conv.py", line 125, in recursion_for_get_group_name
> recursion_for_get_group_name(cur_group_name + [cur_node.attrib['Name']], cur_node)
> [Previous line repeated 1 more time]
> File "remmina_mremoteng_conv.py", line 147, in recursion_for_get_group_name
> PassDecrypt(cur_node.attrib['Password']), True)
> File "remmina_mremoteng_conv.py", line 112, in PassDecrypt
> cipher = Cryptodome.Cipher.AES.new(key, Cryptodome.Cipher.AES.MODE_GCM, nonce=nonce)
> File "/home/ihms/.local/lib/python3.8/site-packages/Cryptodome/Cipher/AES.py", line 232, in new
> return _create_cipher(sys.modules[**name**], key, mode, *args, **kwargs)
> File "/home/ihms/.local/lib/python3.8/site-packages/Cryptodome/Cipher/**init**.py", line 79, in _create_cipher
> return modes[mode](factory, **kwargs)
> File "/home/ihms/.local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 620, in _create_gcm_cipher
> return GcmMode(factory, key, nonce, mac_len, kwargs, ghash_c)
> File "/home/ihms/.local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 188, in **init**
> raise ValueError("Nonce cannot be empty")
> ValueError: Nonce cannot be empty

Had change everythig to ssh
Had combined in one folder
Made the conversation - Got ok but in not Remmina
Lookinf thought code.
Chaged folder on remmina setting to ~/.local/share/remmina

Got it all
