### ISSUE TITLE
Ubuntu 20.04 error

### ISSUE THREAD

**Issue by epigraphe** [mkud/Remmina_mRemoteNG_conv#7]
```
Traceback (most recent call last):
  File "remmina_mremoteng_conv.py", line 225, in <module>
    main() 
  File "remmina_mremoteng_conv.py", line 189, in main
    if PassDecrypt(root.attrib["Protected"]) != 'ThisIsNotProtected':
  File "remmina_mremoteng_conv.py", line 114, in PassDecrypt
    plaintext = cipher.decrypt_and_verify(ciphertext, tag)
  File "/home/at/.local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 567, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/home/at/.local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed
```
What should i do?
Thanks

**Comment by necronaut1** [comment]
Hi, I have the same issue. Any ideas?
Thanks!

`python3 remmina_mremoteng_conv.py -f /home/necroub/remmina_import.xml
Traceback (most recent call last):
  File "remmina_mremoteng_conv.py", line 225, in <module>
    main() 
  File "remmina_mremoteng_conv.py", line 189, in main
    if PassDecrypt(root.attrib["Protected"]) != 'ThisIsNotProtected':
  File "remmina_mremoteng_conv.py", line 114, in PassDecrypt
    plaintext = cipher.decrypt_and_verify(ciphertext, tag)
  File "/home/necroub/.local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 567, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/home/necroub/.local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed
`

**Comment by necronaut1** [comment]
Hi, I seem to have the same issue. Also on Ubuntu 20.04. Remmina installed from ubuntu repo (not from ppa).

> python3 remmina_mremoteng_conv.py -f /home/necroub/remmina_import.xml
Traceback (most recent call last):
  File "remmina_mremoteng_conv.py", line 225, in <module>
    main() 
  File "remmina_mremoteng_conv.py", line 189, in main
    if PassDecrypt(root.attrib["Protected"]) != 'ThisIsNotProtected':
  File "remmina_mremoteng_conv.py", line 114, in PassDecrypt
    plaintext = cipher.decrypt_and_verify(ciphertext, tag)
  File "/home/necroub/.local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 567, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/home/necroub/.local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed

Thanks!

**Comment by FSpark** [comment]
Maybe the number of iterations needs to be adjusted to 10000, which works for me, as it is in the specific xml file.
```python
    key = hashlib.pbkdf2_hmac("sha1", key_from_mRemNG.encode(), salt, 10000, dklen=32)
```

**Comment by seb-bau** [comment]
> Maybe the number of iterations needs to be adjusted to 10000, which works for me, as it is in the specific xml file.
> 
> ```python
>     key = hashlib.pbkdf2_hmac("sha1", key_from_mRemNG.encode(), salt, 10000, dklen=32)
> ```

Can confirm this works! Thank you!

**Comment by FSpark** [comment]
> > Maybe the number of iterations needs to be adjusted to 10000, which works for me, as it is in the specific xml file.
> > ```python
> >     key = hashlib.pbkdf2_hmac("sha1", key_from_mRemNG.encode(), salt, 10000, dklen=32)
> > ```
> 
> Can confirm this works! Thank you!

Haha, knew this would come in handy for somebody—glad it did!

**Comment by mkud** [comment]
Is it system/version specific or can be used in all cases?

What XML file do you mean?

**Comment by FSpark** [comment]
> Is it system/version specific or can be used in all cases?
> 
> What XML file do you mean?

It is the confCons.xml exported by mRemoteNG. It is at the beginning of the file. I am not sure whether it is related to the version. I think it is part of the file metadata.

**Comment by mkud** [comment]
Maybe someone can make a normal universal patch with reading the configuration file. 
I'm just far away from all this and can't even test it properly.
